# -*- coding: utf-8 -*-
"""training_script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1baRTeN4w5fRXadT_FIzI2pFNJ3zErL1R
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import joblib
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

# ==============================================================================
# SECTION 1: CORE MODEL LOGIC & TRAINING (FIXED)
# ==============================================================================

filepath = '/content/diabetes_binary_5050split_health_indicators_BRFSS2015.csv'
label_col = 'Diabetes_binary'

# 1. Load data
columns = pd.read_csv(filepath, nrows=0).columns
dtype_dict = {col: 'float64' for col in columns if col != label_col}
df = pd.read_csv(filepath, dtype=dtype_dict)

# FIX: Explicitly drop any row that has a missing value BEFORE splitting
df = df.dropna()

# FIX: Target columns explicitly by name instead of positional index numbers
X = df.drop(columns=[label_col])  # Features: Everything EXCEPT the label column
y = df[label_col]                 # Label: Exactly the target column

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 2. Setup the baseline pipeline
pipeline = make_pipeline(
    StandardScaler(),
    LogisticRegression(solver='saga', max_iter=2000, random_state=42)
)

# 3. Define the parameter grid
param_grid = {
    'logisticregression__C': [0.01, 0.1, 1.0, 10.0],
    'logisticregression__penalty': ['l1', 'l2']
}

# 4. Run the Grid Search
print("Testing hyperparameter combinations... (This might take a minute)")
grid_search = GridSearchCV(pipeline, param_grid, cv=3, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

# 5. Extract the best configuration
best_logistic_model = grid_search.best_estimator_
print(f"Best settings found: {grid_search.best_params_}\n")

# 6. Predict using the optimized model
y_pred = best_logistic_model.predict(X_test)

# 7. Print optimized metrics
print(f"Optimized Accuracy Score:  {accuracy_score(y_test, y_pred):.2%}")
print(f"Optimized Precision Score: {precision_score(y_test, y_pred, average='weighted'):.2%}")
print(f"Optimized Recall Score:    {recall_score(y_test, y_pred, average='weighted'):.2%}")
print(f"Optimized F1 Score:        {f1_score(y_test, y_pred, average='weighted'):.2%}\n")

# Print console weights output
log_reg_step = best_logistic_model.named_steps['logisticregression']
coefficients = log_reg_step.coef_[0]
feature_names = X.columns

print("Optimized Weights for Each Feature:")
print("-" * 40)
for feature, weight in zip(feature_names, coefficients):
    print(f"{feature:<25} : {weight:.4f}")


# ==============================================================================
# SECTION 2: VISUALIZATION - COEFFICIENTS BARPLOT
# ==============================================================================

# 1. Create a clean Pandas DataFrame of your features and weights
coef_df = pd.DataFrame({
    'Feature': X.columns,
    'Weight': best_logistic_model.named_steps['logisticregression'].coef_[0]
})

# 2. Sort the features by weight so the chart goes from highest risk to lowest risk
coef_df = coef_df.sort_values(by='Weight', ascending=False).reset_index(drop=True)

# 3. Set up the plotting style and canvas size
sns.set_theme(style="whitegrid")
plt.figure(figsize=(12, 8))

# 4. Create a dynamic color palette: Red for positive risk, Blue for negative/protective
colors = np.where(coef_df['Weight'] > 0, '#d9534f', '#428bca')

# 5. Draw the horizontal bar chart
barplot = sns.barplot(
    x='Weight',
    y='Feature',
    data=coef_df,
    palette=colors,
    hue='Feature',
    legend=False
)

# 6. Add a vertical line at 0.00 to clearly separate positive and negative impacts
plt.axvline(x=0, color='black', linestyle='--', linewidth=1)

# 7. Add professional titles and labels
plt.title('Diabetes Risk Indicators\n(Optimized Logistic Regression Coefficients)', fontsize=16, fontweight='bold', pad=15)
plt.xlabel('Coefficient Weight (Strength of Impact)', fontsize=12, labelpad=10)
plt.ylabel('Health Indicator / Feature', fontsize=12)

# 8. Loop through the bars to add the exact numerical value next to each bar
for index, row in coef_df.iterrows():
    weight = row['Weight']
    if weight >= 0:
        barplot.text(weight + 0.01, index, f'{weight:.3f}', color='black', ha='left', va='center', fontsize=10)
    else:
        barplot.text(weight - 0.01, index, f'{weight:.3f}', color='black', ha='right', va='center', fontsize=10)

plt.tight_layout()
plt.show()  # Renders the Barplot cleanly in Colab


# ==============================================================================
# SECTION 3: VISUALIZATION - CONFUSION MATRIX HEATMAP
# ==============================================================================

# 1. Compute the raw confusion matrix values
cm = confusion_matrix(y_test, y_pred)

# 2. Set up the canvas style and size
sns.set_theme(style="white")
plt.figure(figsize=(8, 6))

# 3. Create the heatmap plot
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=['No Diabetes (0)', 'Diabetes (1)'],
    yticklabels=['No Diabetes (0)', 'Diabetes (1)']
)

# 4. Add clear, professional titles and axis labels
plt.title('Confusion Matrix Heatmap\n(Optimized Logistic Regression Results)', fontsize=14, fontweight='bold', pad=15)
plt.xlabel('Predicted Label (What the Model Guessed)', fontsize=12, labelpad=10)
plt.ylabel('Actual Label (The Patient\'s True Status)', fontsize=12, labelpad=10)

plt.tight_layout()
plt.show()  # Renders the Heatmap cleanly in Colab


# ==============================================================================
# SECTION 4: SAVE PRODUCTION MODEL FILE
# ==============================================================================

joblib.dump(best_logistic_model, 'diabetes_model.pkl')
print("\nModel pipeline successfully saved to 'diabetes_model.pkl'")