# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HTQ4xj4JpeTJ4EXgJP8fLOVnzuIK7uY3
"""

import gradio as gr
import joblib
import numpy as np
import pandas as pd

# 1. Load the saved model pipeline
model = joblib.load("diabetes_model.pkl")

# 2. Define the prediction function
def predict_diabetes(
    high_bp, high_chol, chol_check, bmi, smoker, stroke, heart_disease,
    phys_activity, fruits, veggies, hvy_alcohol, any_healthcare, no_doc_cost,
    gen_hlth, ment_hlth, phys_hlth, diff_walk, sex, age, education, income
):
    # Construct a single row DataFrame matching the exact features the model expects
    input_data = pd.DataFrame([{
        'HighBP': high_bp, 'HighChol': high_chol, 'CholCheck': chol_check, 'BMI': bmi,
        'Smoker': smoker, 'Stroke': stroke, 'HeartDiseaseorAttack': heart_disease,
        'PhysActivity': phys_activity, 'Fruits': fruits, 'Veggies': veggies,
        'HvyAlcoholConsump': hvy_alcohol, 'AnyHealthcare': any_healthcare,
        'NoDocbcCost': no_doc_cost, 'GenHlth': gen_hlth, 'MentHlth': ment_hlth,
        'PhysHlth': phys_hlth, 'DiffWalk': diff_walk, 'Sex': sex, 'Age': age,
        'Education': education, 'Income': income
    }])

    # Cast everything to float64 just like the training step
    input_data = input_data.astype('float64')

    # Make prediction
    prediction = model.predict(input_data)[0]
    probabilities = model.predict_proba(input_data)[0]

    # Return a friendly dictionary showing probability
    labels = ['No Diabetes', 'Diabetes']
    return {labels[i]: float(probabilities[i]) for i in range(2)}

# 3. Build the User Interface
# We use sliders for numerical columns and binary 0/1 inputs for yes/no checkboxes
inputs = [
    gr.Slider(0, 1, step=1, label="High Blood Pressure (0=No, 1=Yes)"),
    gr.Slider(0, 1, step=1, label="High Cholesterol (0=No, 1=Yes)"),
    gr.Slider(0, 1, step=1, label="Cholesterol Check in Past 5 Years (0=No, 1=Yes)"),
    gr.Slider(10, 50, step=1, label="BMI"),
    gr.Slider(0, 1, step=1, label="Smoker (0=No, 1=Yes)"),
    gr.Slider(0, 1, step=1, label="Had a Stroke? (0=No, 1=Yes)"),
    gr.Slider(0, 1, step=1, label="Heart Disease or Attack History (0=No, 1=Yes)"),
    gr.Slider(0, 1, step=1, label="Physical Activity in Past 30 Days (0=No, 1=Yes)"),
    gr.Slider(0, 1, step=1, label="Consumes Fruits 1+ times/day (0=No, 1=Yes)"),
    gr.Slider(0, 1, step=1, label="Consumes Veggies 1+ times/day (0=No, 1=Yes)"),
    gr.Slider(0, 1, step=1, label="Heavy Alcohol Consumer (0=No, 1=Yes)"),
    gr.Slider(0, 1, step=1, label="Has Any Healthcare Coverage? (0=No, 1=Yes)"),
    gr.Slider(0, 1, step=1, label="Skipped Doctor due to Cost? (0=No, 1=Yes)"),
    gr.Slider(1, 5, step=1, label="General Health Rating (1=Excellent, 5=Poor)"),
    gr.Slider(0, 30, step=1, label="Days of Poor Mental Health (Past 30 days)"),
    gr.Slider(0, 30, step=1, label="Days of Poor Physical Health (Past 30 days)"),
    gr.Slider(0, 1, step=1, label="Serious Difficulty Walking? (0=No, 1=Yes)"),
    gr.Slider(0, 1, step=1, label="Sex (0=Female, 1=Male)"),
    gr.Slider(1, 13, step=1, label="Age Category (1=18-24, 13=80+)"),
    gr.Slider(1, 6, step=1, label="Education Level (1=Never attended, 6=College graduate)"),
    gr.Slider(1, 8, step=1, label="Income Bracket (1=Lowest, 8=Highest)")
]

outputs = gr.Label(num_top_classes=2, label="Prediction Probability")

# 4. Launch the application
app = gr.Interface(
    fn=predict_diabetes,
    inputs=inputs,
    outputs=outputs,
    title="Diabetes Risk Predictor",
    description="An optimized Logistic Regression model trained on BRFSS survey indicators."
)

app.launch()
